### ISSUE TITLE
Implement Sandboxing on FreeBSD using capsicum

### ISSUE THREAD

**Issue by loganaden** [brynet/file#1]
Hi,

Here's a small patch for FreeBSD's capsicum. It's interesting to point out that FreeBSD does not have systrace or seccomp-bpf.

The advantage of capsisum is that it restricts operations on file descriptors, so operations like open() and socket() fail in a sandbox unless explicitly allowed to through other capsicum API. The initial code works well with multiple file I tested on FreeBSD 10:

http://elandsys.com/~logan/openbsd_file_capsicum.diff

**Comment by brynet** [comment]
I'm not sure if Capsicum is doing as much as systrace(4) or seccomp-bpf, but this is probably better than just privsep alone on FreeBSD.

Committed a slightly revised diff, but leaving this issue open for now.

**Comment by brynet** [comment]
Logan, I've reverted this until we can better understand if Capsicum can be appropriately used here.
