### ISSUE TITLE
macOS: build errors

### ISSUE THREAD

**Issue by grylem** [brynet/file#3]
Hi.
file.c:388:7: warning: implicit declaration of function 'setresgid' is invalid in C99
file.c:390:7: warning: implicit declaration of function 'setresuid' is invalid in C99

magic-load.c:694:35: warning: passing 'int64_t *' (aka 'long long *') to parameter of type 'uint64_t *'
      (aka 'unsigned long long *') converts between pointers to integer types with different sign

Undefined symbols for architecture x86_64:
  "_setresgid", referenced from:
      _child in file.o
  "_setresuid", referenced from:
      _child in file.o

Please add setresgid and setresuid to compat folder and configure script.
Thanks.

**Comment by brynet** [comment]
`setresgid(2)/setresuid(2)` are system calls on at least *BSD/Linux. It's unfortunate that macOS has no implementation of these.

I have no macOS systems to test on, if you would like to add compat for these functions, I suggest you make a fork the project.

**Comment by brynet** [comment]
NetBSD also apparently doesn't support these functions, but has no equivalent support for "sandboxing" so it would be relying exclusively on privsep/privdrop.

**Comment by brynet** [comment]
I've changed my mind on this and committed a fix using an implementation from Kristaps Dzonsons. This should at least allow it to compile on macOS and NetBSD, baring any other build problems.

fb8158ea31d67706be1c29247373675a69d90ed7

I will still note that these platforms are relying exclusively on privsep/privdrop here, which addresses any invocations of file(1) as root. Without any platform equivalent to `pledge(2)` or `seccomp-bpf`, file(1) is still unprotected from potentially malicious input files in the same way as the libmagic file.

**Comment by grylem** [comment]
Thank you very much.
Only one thing left
`magic-load.c:694:35: warning: passing 'int64_t *' (aka 'long long *') to parameter of type 'uint64_t *'
      (aka 'unsigned long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
                endptr = magic_strtoull(cp + 1, &ml->type_operand);
                                                ^~~~~~~~~~~~~~~~~
./magic.h:221:47: note: passing argument to parameter here
char            *magic_strtoull(const char *, uint64_t *);
                                                        ^`
Regards.

**Comment by brynet** [comment]
This appears to be just a warning, it shouldn't prevent it from building. Correct?

As this is not a problem introduced by this port, patches should be sent upstream to the OpenBSD mailing lists.

https://www.openbsd.org/report.html
https://www.openbsd.org/mail.html

But please don't send portability issues there, only patches tested on OpenBSD.

**Comment by grylem** [comment]
Yes you are right it's only warning and this is not a port problem.
Thanks again for making the macOS port.
Best Regards.
